### ISSUE TITLE
Delay in receiving published messages

### ISSUE THREAD

**Issue by deena-philip** [davidepianca98/KMQTT#40]
While testing the MQTT publish and subscribe functions in KMM I'm seeing a delay of more than 1-3 minutes. Please guide me on how this can be fixed.

**Comment by boris-senapt** [comment]
Can you provide an example? I've seen similar behaviour when using `run()` as it takes a lock in a tight loop. 

I found using a loop with a `sleep` unblocked things.

**Comment by deena-philip** [comment]
@boris-senapt 
It happens when `publish(...)` is called after `run()`. I'm using coroutines in my sample project.

Can you show me a sample code on how to publish after `run()`?

**Comment by boris-senapt** [comment]
I don't use continues - instead opting for Java21 virtual threads. But my code is essentially calling `step()` then `sleep`.  Any amount of sleep will do as it deschedule the thread. 

The issue is, I think, that `run` is a tight loop and takes the lock in `step` each time. 

I imagine a fair lock would also resolve.

**Comment by deena-philip** [comment]
@boris-senapt Let me try it out. Thanks for the help.

**Comment by deena-philip** [comment]
Hi @boris-senapt, just tried adding a delay and calling step() in a loop from coroutine itself and it works fine now.
`CoroutineScope(Dispatchers.IO).launch {
                while (isActive) {
                    client.step()
                    delay(200)
                }
            }
`
